# Chart values for the Camunda Platform 8 Helm chart in separate ingress setup. 
# Note: you can change the global.image.tag version value as needed.
global:
  image:
    tag: latest

  identity:
    auth:
      publicIssuerUrl: "https://keycloak.c8.dev.local/auth/realms/camunda-platform"
      connectors:
        existingSecret: dev-identity-secrets
      operate:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://operate.c8.dev.local"
      tasklist:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://tasklist.c8.dev.local"
      optimize:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://optimize.c8.dev.local"
      webModeler:
        redirectUrl: "https://modeler.c8.dev.local"
 
# Reduce Zeebe and Gateway replicas and resources to make it run locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi
 
zeebe-gateway:
  replicas: 1
  ingress:
    enabled: true
    host: "zeebe.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
operate:
  # Configure resources for local testing.
  resources:
    requests:
      cpu: 500m
      memory: 400Mi
    limits:
      cpu: 1500m
      memory: 1Gi
  ingress:
    enabled: true
    host: "operate.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
tasklist:
#  # Configure resources for local testing.
#  resources:
#    requests:
#      cpu: 500m
#      memory: 500Mi
#    limits:
#      cpu: 1000m
#      memory: 1Gi
  ingress:
    enabled: true
    host: "tasklist.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
optimize:
#  # Configure resources for local testing.
#  resources:
#    requests:
#      cpu: 750m
#      memory: 768Mi
#    limits:
#      cpu: 1500m
#      memory: 1536Mi
  ingress:
    enabled: true
    host: "optimize.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"
 
identity:
  fullURL: "https://identity.c8.dev.local"
#  # Configure resources for local testing.
#  resources:
#    requests:
#      cpu: 750m
#      memory: 500Mi
#    limits:
#      cpu: 1500m
#      memory: 1536Mi
  keycloak:
    extraEnvVars:
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
    ingress:
      enabled: true
      hostname: "keycloak.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"
    auth:
      existingSecret: dev-identity-keycloak-secrets
    postgresql:
      auth:
        existingSecret: dev-identity-keycloak-postgresql-secrets
  ingress:
    enabled: true
    host: "identity.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"

webModeler:
  enabled: true
  image:
    tag: 8.2.3
    pullSecrets:
      - name: dev-c8-registry
  restapi:
    mail:
      # Restapi.mail.smtpHost defines the host name of the SMTP server to be used by Web Modeler
      smtpHost: ""
      # Restapi.mail.smtpPort defines the port number of the SMTP server
      smtpPort: 587
      # Restapi.mail.smtpUser can be used to provide a user for the SMTP server
      smtpUser: ""
      # Restapi.mail.smtpPassword can be used to provide a password for the SMTP server
      smtpPassword: ""
      # Restapi.mail.smtpTlsEnabled if true, enforces TLS encryption for SMTP connections (using STARTTLS)
      smtpTlsEnabled: true
      # Restapi.mail.fromAddress defines the email address that will be displayed as the sender of emails sent by Web Modeler
      fromAddress: "no-reply@camunda.com"
      # Restapi.mail.fromName defines the name that will be displayed as the sender of emails sent by Web Modeler
      fromName: "Camunda Platform"
    env:
##      Configuration for DEBUG logging:
#      - name: LOGGING_LEVEL_IO_GRPC
#        value: TRACE
      - name: ZEEBE_CA_CERTIFICATE_PATH
        value: "/home/node/dev.c8.separated.crt"
    extraVolumes:
      - name: dev-c8-separated
        secret:
          secretName: dev-c8-separated
    extraVolumeMounts:
      - name: dev-c8-separated
        mountPath: "/home/node/dev.c8.separated.crt"
        subPath: tls.crt
#    # Configure resources for local testing.
#    resources:
#      requests:
#        cpu: 500m
#        memory: 768Mi
#      limits:
#        cpu: 1000m
#        memory: 1536Mi
  webapp:
    env:
      - name: ZEEBE_CLIENT_SSL_ROOT_CERTS_PATH
        value: "/home/node/dev.c8.separated.crt"
    extraVolumes:
      - name: dev-c8-separated
        secret:
          secretName: dev-c8-separated
    extraVolumeMounts:
      - name: dev-c8-separated
        mountPath: "/home/node/dev.c8.separated.crt"
        subPath: tls.crt
  ingress:
    enabled: true
    webapp:
      host: "modeler.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"
    websockets:
      host: "websockets.c8.dev.local"
      tls:
        enabled: true
        secretName: "dev-c8-separated"

postgresql:
  enabled: true
  auth:
    existingSecret: dev-modeler-postgresql-secrets

connectors:
#  # Configure resources for local testing.
#  resources:
#    requests:
#      cpu: 250m
#      memory: 256Mi
#    limits:
#      cpu: 500m
#      memory: 768Mi
  ingress:
    enabled: true
    host: "connectors.c8.dev.local"
    tls:
      enabled: true
      secretName: "dev-c8-separated"

# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
#  imageTag: 7.17.3  # Uncomment this line and set a value if you want to override the default chart value.
  replicas: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 8Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
