kind: ConfigMap
apiVersion: v1
metadata:
  name: optimize-configuration
  namespace: default
data:
  environment-config.yaml: |
    ---
    ###############################################################################
    #                                                                             #
    #                     Optimize Environment Configuration                      #
    #                                                                             #
    ###############################################################################

    # Note: for all possible configuration options please have a look
    #       at the Optimize documentation:
    #       https://docs.camunda.org/optimize/${docs.version}/technical-guide/setup/configuration/
    opensearch:
      connection:
        nodes:
          - host:
            port: