# TODO: Later we should move to Testkube.
# https://github.com/kubeshop/testkube
name: "Test - Integration - Kubernetes"

on:
  pull_request:
    paths:
    - '.github/**'
    - '.tool-versions'
    - 'charts/**'
    - 'go.*'
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.scenario.title }}
    if: github.ref == 'refs/heads/main' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        scenario:
        - title: ChartWithDefaultValues
          dir: chart-with-default-values
          description: Test Camunda Platform Helm chart default values
        - title: ChartUpgrade
          dir: chart-upgrade
          description: Test Camunda Platform Helm chart upgrade
        - title: ChartWithCustomValues
          dir: chart-with-custom-values
          description: Test Camunda Platform Helm chart custom values
        - title: ChartWithKeycloakV19
          dir: chart-with-keycloak-v19
          description: Test Camunda Platform Helm chart with next supported Keycloak version v8.2
        - title: ChartWithWebModeler
          dir: chart-with-web-modeler
          description: Test Camunda Platform Helm chart with WebModeler enabled which is still beta
          dockerLogin: true
    steps:
    - uses: actions/checkout@v3
    - name: Login to GKE
      uses: ./.github/actions/gke-login
      with:
        credentials-json: '${{ secrets.GCP_CREDENTIALS }}'
        cluster-name: ${{ secrets.GKE_CLUSTER }}
        cluster-location: ${{ secrets.GKE_ZONE }}
    - name: Run Test Scenario
      uses: ./.github/actions/test-scenario-run
      with:
        test-scenario-dir: ${{ matrix.scenario.dir }}
        docker-login-enabled: ${{ matrix.scenario.dockerLogin }}
        docker-login-username: ${{ secrets.CAMUNDA_REGISTRY_USER }}
        docker-login-password: ${{ secrets.CAMUNDA_REGISTRY_PASSWORD }}
        delete-namespace: ${{ !secrets.ACTIONS_STEP_DEBUG }}
